### PR TITLE
HW 7 and CLASS WORK 7 &

### PR DESCRIPTION
**Pull request by Bogdangarantov**

### CODE REVIEW

**Review by mecchmatProjects — COMMENTED** [review]
Who are You?

**Comment by Bogdangarantov** [comment]
Хариш Богдан Комп мат 2 , 3 курс


> Who are You?

**Review by mecchmatProjects — CHANGES_REQUESTED** [review]
who are You?

**Comment by Bogdangarantov** [comment]
I'm harysh bogdan I told u this in comment behind

**Comment by Bogdangarantov** [comment]
The 3 course of comp math , 2 group

**Review by mecchmatProjects — APPROVED** [review]
ok. at last...

**Comment by Bogdangarantov** [comment]
Sorry, i`ll tell u my  info in the every next time

**Pull request merged**
